badd Session.vim

badd examples/actors.lua
badd examples/colors.lua
badd examples/font.lua
badd examples/sound-sdl.lua
badd examples/sound.lua
badd examples/spinner.lua
badd examples/sprite.lua
badd examples/texture.lua
badd private/will.lua
badd tests/base_test.lua
badd tests/v2_test.lua
badd actor_scene.lua
badd base.lua
badd game.lua
badd graphics.lua
badd kernel.lua
badd module.lua
badd v2.lua
